name: Build for target

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       target: thumbv7m-none-eabi
       override: true
    - uses: actions-rs/cargo@v1
      with:
       use-cross: true
       command: build
       args: --target thumbv7m-none-eabi
